# Inserts a blank line between shell prompts
add_newline = false

format = """\\[$directory\\] $character"""

# format="""$all $directory$character\

# """
right_format = """$git_status$python
"""

# Replace the "❯" symbol in the prompt with "➜" "▶"
# The name of the module we are configuring is "character"
[character]
  error_symbol = "[x](bold red) "
  # vicmd_symbol = "[❮](bold blue) "
  vicmd_symbol = "[\\$](bold green) "
  # success_symbol = "[❯](bold blue)"
  success_symbol = "[\\$](bold cyan)"
  # success_symbol = "[ ](bold red)"

[python]
  # symbol = "  "
  symbol = ""
  pyenv_version_name = true
  style = "purple"

[php]
  symbol = " "
  # symbol = "Php "

[rust]
  symbol = " "

[perl]
  symbol = " "

[golang]
  symbol = " "

[c]
  symbol = " "
# Disable the package module, hiding it from the prompt completely
[package]
  disabled = false

[time]
  disabled = false
  format = '[\[ $time \]]($style) '
  time_format = "%T"
  utc_time_offset = "-5"
  time_range = "10:00:00-14:00:00"
