

# Inserts a blank line between shell prompts
add_newline = true
# format="$all$directory$character"
right_format = """$git_status\
$hg_branch\
"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
  error_symbol = "[✗](bold red) "
  vicmd_symbol = "[❮](bold blue) "


# Disable the package module, hiding it from the prompt completely
[package]
  disabled = false



[time]
disabled = true
format = '[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"
