# Inserts a blank line between shell prompts
add_newline = false
# format="$all$directory$character"
right_format = """
$git_status\
"""

# Replace the "❯" symbol in the prompt with "➜" "▶"
# The name of the module we are configuring is "character"
[character]
  error_symbol = "[](bold red) "
  vicmd_symbol = "[❮](bold blue) "
  success_symbol = "[❯](bold #5cb281)"
  # success_symbol = "[ ](bold #5cb281)"


# Disable the package module, hiding it from the prompt completely
[package]
  disabled = true



[time]
  disabled = true
  format = '[\[ $time \]]($style) '
  # time_format = "%T"
  utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"
